In [3]:
!pip install numpy


In [4]:
import numpy as np

In [7]:
import numpy as np

arr1 = np.arange(1, 11)
print(arr1)

arr2 = np.random.randint(1, 10, (3, 3))
print(arr2)


[ 1  2  3  4  5  6  7  8  9 10]
[[5 6 1]
 [4 6 7]
 [9 6 5]]


In [8]:
print("Sum:", arr1.sum())
print("Mean:", arr1.mean())
print("Max:", arr1.max())

arr_multiplied = arr1 * 2
print(arr_multiplied)

arr_replaced = arr1.copy()
arr_replaced[arr_replaced > 5] = 0
print(arr_replaced)


Sum: 55
Mean: 5.5
Max: 10
[ 2  4  6  8 10 12 14 16 18 20]
[1 2 3 4 5 0 0 0 0 0]
